version: '2'
services:

  build_ubuntu:
    build: ./beegfs_mon
    image: ubuntu_beegfs_mon
    networks:
      - eseries_perf_analyzer

  beegfs_mon:
    image: ubuntu_beegfs_mon
    stdin_open: true
    tty: true
    container_name: beegfs_mon
    restart: unless-stopped
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./beegfs_mon/beegfs-mon.conf:/etc/beegfs/beegfs-mon.conf:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

# TODO (bdustin): Update this before rebasing with "persistent_network" changes
networks:
  eseries_perf_analyzer:
    external: true