version: '2'
services:

  beegfs_mon:
    image: ${PROJ_NAME}-plugin/beegfs_monitoring/beegfs-mon
    stdin_open: true
    tty: true
    container_name: beegfs_mon
    restart: unless-stopped
    networks:
      - eseries_perf_analyzer
    volumes:
      - ./beegfs_mon/beegfs-mon.conf:/etc/beegfs/beegfs-mon.conf:ro
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

networks:
  eseries_perf_analyzer:
    external: true