{
 "title": "BeeGFS Overview",
 "tags": [ "BeeGFS Plugin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BeeGFS Metadata Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nodeID" ], "type": "tag" }
     ],
     "measurement": "meta",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Metadata Server Work Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_nodeID - Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$tag_nodeID - Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResMeta",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Storage Server Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_nodeID - Reads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "diskReadBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$tag_nodeID - Writes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "diskWriteBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BeeGFS Storage Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nodeID" ], "type": "tag" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Server Work Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_nodeID - Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "$tag_nodeID - Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ ($__interval_ms / 1000)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Targets (last 30 seconds)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageTargetID" ], "type": "tag" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT \"nodeID\" as \"BeeGFS Node\", \"targetConsistencyState\" as \"Consistency State\", \"diskSpaceFree\" as \"GiB Free\", \"diskSpaceTotal\" as \"GiB Total\", (\"diskSpaceFree\" / \"diskSpaceTotal\") * 100 as \"GiB Percentage\", \"inodesFree\" as \"Free Inodes\", \"inodesTotal\" as \"Total Inodes\", (\"inodesFree\" / \"inodesTotal\") * 100 as \"Inodes Percentage\" FROM \"storageTargets\" WHERE time > now() - 30s GROUP BY \"storageTargetID\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "targetConsistencyState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  { "title": "Client Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Metadata Operations By Client",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "metaClientOpsByNode",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Operations By Client",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageClientOpsByNode",
     "select": [
      [
       { "params": [ "sum" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}