{
 "title": "BeeGFS Storage Server",
 "tags": [ "BeeGFS Plugin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "storageID",
    "label": "Storage ID",
    "query": "show tag values from storage with key = \"nodeID\" "
   }
  ]
 },
 "panels": [
  { "title": "Storage Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "diskReadBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "diskWriteBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "query": "SELECT last(\"diskSpaceFree\") FROM \"storage\" WHERE \"nodeID\" =~ /^$storageID$/ AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "netRecvBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "netSendBytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Work Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "workRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    },
    {
     "alias": "Queued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "highResStorage",
     "select": [
      [
       { "params": [ "queuedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Responding",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "isResponding" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Targets (last 30 seconds)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "storageTargetID" ], "type": "tag" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT \"targetConsistencyState\" as \"Consistency State\", \"diskSpaceFree\" / (1024*1024*1024) as \"GiB Free\", \"inodesFree\" as \"Inodes Free\" FROM \"storageTargets\" WHERE \"nodeID\" =~ /^$storageID$/ AND time > now() - 30s GROUP BY \"storageTargetID\" ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "targetConsistencyState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "nodeID", "operator": "=~", "value": "/^$storageID$/" }
     ]
    }
   ]
  }
 ]
}