{
 "title": "BeeGFS-DF",
 "description": "Aggregated space utilization on storage targets.",
 "tags": [ "BeeGFS Plugin" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "BeeGFS Reported Target Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Used Space on Storage Targets",
   "type": "graph",
   "description": "Storage target utilization as reported by BeeGFS (i.e. beegfs-df).",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT max(\"diskSpaceTotal\") - max(\"diskSpaceFree\") FROM \"storageTargets\" WHERE $timeFilter GROUP BY time($__interval), \"storageTargetID\" fill(none)",
     "select": [
      [
       { "params": [ "diskSpaceTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Space on Storage Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "select": [
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Space on Storage Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "select": [
      [
       { "params": [ "diskSpaceTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "BeeGFS Reported Inode Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Used Inodes on Storage Targets",
   "type": "graph",
   "description": "Storage target utilization as reported by BeeGFS (i.e. beegfs-df).",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT max(\"inodesTotal\") - max(\"inodesFree\") FROM \"storageTargets\" WHERE $timeFilter GROUP BY time($__interval), \"storageTargetID\" fill(none)",
     "select": [
      [
       { "params": [ "diskSpaceTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "diskSpaceFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free Inodes on Storage Targets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT max(\"diskSpaceTotal\") FROM \"storageTargets\" WHERE $timeFilter GROUP BY time($__interval), \"storageTargetID\" fill(none)",
     "select": [
      [
       { "params": [ "inodesFree" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Inodes on Storage Targets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_storageTargetID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageTargetID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storageTargets",
     "query": "SELECT max(\"diskSpaceTotal\") FROM \"storageTargets\" WHERE $timeFilter GROUP BY time($__interval), \"storageTargetID\" fill(none)",
     "select": [
      [
       { "params": [ "inodesTotal" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}